[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

# Optional: Redirect all routes to index.html (needed for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
