[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"  # <-- just "dist", relative to frontend folder

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
