redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "D:\\web\\web\\E-Fiesta-2k25\\frontend\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "D:\\web\\web\\E-Fiesta-2k25\\frontend"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]